# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "33c92f612ffe7775b25b4b807ddc9d2f"
name = "checkout-extension-banner"
handle = "checkout-extension-banner-1"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
